use can_dbc_pest::{Pair, Rule};

use crate::parser;
use crate::parser::{expect_empty, DbcResult};

/// Version generated by DB editor
#[derive(Clone, Debug, Default, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Version(pub String);

impl Version {
    /// Parse version: VERSION "string"
    pub(crate) fn parse(pair: Pair<Rule>) -> DbcResult<Version> {
        let mut pairs = pair.into_inner();
        let version_str = parser::parse_str(parser::next_rule(&mut pairs, Rule::quoted_str)?);
        expect_empty(&mut pairs)?;

        Ok(Version(version_str))
    }
}
